  services:
    web:
      depends_on:
        - server
      platform: linux/amd64
      build: ./web
      restart: on-failure:5
      ports:
        - "${WEB_PORT}:${WEB_DOCKER_PORT}"
      volumes:
        - ./web:/app

    server:
      depends_on:
        - db
      build: ./server
      ports:
        - "${SV_PORT}:${SV_PORT}"
      environment:
        SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${POSTGRES_DB}
        SPRING_DATASOURCE_USERNAME: ${DB_USER}
        SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}

    db:
      image: postgres:latest
      platform: linux/amd64
      restart: on-failure:5
      environment:
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_USER: ${DB_USER}
        POSTGRES_PASSWORD: ${DB_PASSWORD}
      volumes:
        - ./data/sql:/docker-entrypoint-initdb.d
      ports:
        - "${DB_PORT}:5432"