services:
  web:
    depends_on:
      - server
    platform: linux/amd64
    build: ./web
    ports:
      - "${WEB_PORT}:${WEB_DOCKER_PORT}"
    volumes:
      - ./web:/app

  server:
    depends_on:
      db:
        condition: service_healthy
    build: ./server
    ports:
      - "${SV_PORT}:${SV_PORT}"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://vyt-db-1:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}

  db:
    image: postgres:latest
    platform: linux/amd64
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./data/sql:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "${DB_PORT}:5432"
